[project]
name = "smcdet"
version = "0.1.0"
description = "Probabilistic object detection with sequential Monte Carlo"
authors = [
    {name = "Tim White", email = "twhit@umich.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "absl-py (==2.2.2)",
    "aiohappyeyeballs (==2.6.1)",
    "aiohttp (==3.11.16)",
    "aiosignal (==1.3.2)",
    "antlr4-python3-runtime (==4.9.3)",
    "arviz (==0.19.0)",
    "asciitree (==0.3.3)",
    "astropy (==6.1.7)",
    "astropy-healpix (==1.1.2)",
    "astropy-iers-data (==0.2025.4.7.0.35.30)",
    "asttokens (==2.4.1)",
    "async-timeout (==5.0.1)",
    "attrs (==25.3.0)",
    "backcall (==0.2.0)",
    "black (==24.8.0)",
    "bokeh (==3.7.2)",
    "boto3 (==1.37.30)",
    "botocore (==1.37.30)",
    "certifi (==2025.1.31)",
    "cfgv (==3.4.0)",
    "charset-normalizer (==3.4.1)",
    "click (==8.1.7)",
    "cloudpickle (==3.1.1)",
    "colossus (==1.3.8)",
    "comm (==0.2.2)",
    "contourpy (==1.2.1)",
    "cycler (==0.12.1)",
    "dask (==2025.3.0)",
    "debugpy (==1.8.1)",
    "decorator (==5.1.1)",
    "distlib (==0.3.8)",
    "dm-tree (==0.1.8)",
    "einops (==0.8.1)",
    "executing (==2.0.1)",
    "fasteners (==0.19)",
    "filelock (==3.15.4)",
    "filetype (==1.2.0)",
    "fire (==0.7.0)",
    "flake8 (==7.1.1)",
    "fonttools (==4.51.0)",
    "frozenlist (==1.5.0)",
    "fsspec (==2024.5.0)",
    "future (==1.0.0)",
    "galsim (==2.7.1)",
    "gitdb (==4.0.12)",
    "gitpython (==3.1.44)",
    "grpcio (==1.71.0)",
    "h5netcdf (==1.3.0)",
    "h5py (==3.11.0)",
    "huggingface-hub (==0.24.7)",
    "hydra-core (==1.3.2)",
    "identify (==2.6.0)",
    "idna (==3.7)",
    "imageio (==2.34.1)",
    "importlib-metadata (==8.6.1)",
    "ipykernel (==6.29.4)",
    "ipython (==8.12.3)",
    "isort (==5.13.2)",
    "jedi (==0.19.1)",
    "jinja2 (==3.1.6)",
    "jmespath (==1.0.1)",
    "joblib (==1.4.2)",
    "jupyter-client (==8.6.2)",
    "jupyter-core (==5.7.2)",
    "kiwisolver (==1.4.5)",
    "lazy-loader (==0.4)",
    "lightning-utilities (==0.14.3)",
    "line-profiler (==4.1.3)",
    "locket (==1.0.0)",
    "lsstdesc-coord (==1.3.0)",
    "markdown (==3.7)",
    "markupsafe (==2.1.5)",
    "matplotlib (==3.8.4)",
    "matplotlib-inline (==0.1.7)",
    "mccabe (==0.7.0)",
    "mpmath (==1.3.0)",
    "multidict (==6.2.0)",
    "mypy-extensions (==1.0.0)",
    "narwhals (==1.34.1)",
    "nest-asyncio (==1.6.0)",
    "networkx (==3.3)",
    "nodeenv (==1.9.1)",
    "numcodecs (==0.13.1)",
    "numpy (==1.26.4)",
    "nvidia-cublas-cu12 (==12.6.4.1)",
    "nvidia-cuda-cupti-cu12 (==12.6.80)",
    "nvidia-cuda-nvrtc-cu12 (==12.6.77)",
    "nvidia-cuda-runtime-cu12 (==12.6.77)",
    "nvidia-cudnn-cu12 (==9.5.1.17)",
    "nvidia-cufft-cu12 (==11.3.0.4)",
    "nvidia-cufile-cu12 (==1.11.1.6)",
    "nvidia-curand-cu12 (==10.3.7.77)",
    "nvidia-cusolver-cu12 (==11.7.1.2)",
    "nvidia-cusparse-cu12 (==12.5.4.2)",
    "nvidia-cusparselt-cu12 (==0.6.3)",
    "nvidia-nccl-cu12 (==2.26.2)",
    "nvidia-nvjitlink-cu12 (==12.6.85)",
    "nvidia-nvtx-cu12 (==12.6.77)",
    "omegaconf (==2.3.0)",
    "opencv-python (==4.10.0.84)",
    "opencv-python-headless (==4.10.0.84)",
    "packaging (==24.0)",
    "pandas (==2.2.2)",
    "parso (==0.8.4)",
    "partd (==1.4.2)",
    "pathspec (==0.12.1)",
    "pexpect (==4.9.0)",
    "pickleshare (==0.7.5)",
    "pillow (==10.3.0)",
    "pillow-heif (==0.22.0)",
    "pip (==22.0.2)",
    "pip3-autoremove (==1.2.2)",
    "platformdirs (==4.2.2)",
    "pre-commit (==3.8.0)",
    "prompt-toolkit (==3.0.43)",
    "propcache (==0.3.1)",
    "protobuf (==6.30.2)",
    "psutil (==6.0.0)",
    "ptyprocess (==0.7.0)",
    "pure-eval (==0.2.2)",
    "py-cpuinfo (==9.0.0)",
    "pybboxes (==0.1.6)",
    "pybind11 (==2.13.6)",
    "pycodestyle (==2.12.1)",
    "pyerfa (==2.0.1.5)",
    "pyflakes (==3.2.0)",
    "pygments (==2.18.0)",
    "pyparsing (==3.1.2)",
    "python-dateutil (==2.9.0.post0)",
    "python-dotenv (==1.1.0)",
    "pytorch-lightning (==2.5.1)",
    "pytz (==2024.1)",
    "pyvo (==1.6.2)",
    "pyyaml (==6.0.2)",
    "pyzmq (==26.0.3)",
    "reproject (==0.14.1)",
    "requests (==2.32.3)",
    "requests-toolbelt (==1.0.0)",
    "roboflow (==1.1.60)",
    "s3transfer (==0.11.4)",
    "sahi (==0.11.22)",
    "scikit-image (==0.23.2)",
    "scikit-learn (==1.6.1)",
    "scipy (==1.15.1)",
    "seaborn (==0.13.2)",
    "setuptools (==71.1.0)",
    "shapely (==2.1.0)",
    "six (==1.16.0)",
    "smmap (==5.0.2)",
    "stack-data (==0.6.3)",
    "sympy (==1.14.0)",
    "tensorboard (==2.19.0)",
    "tensorboard-data-server (==0.7.2)",
    "termcolor (==3.0.1)",
    "terminaltables (==3.1.10)",
    "thop (==0.1.1.post2209072238)",
    "threadpoolctl (==3.6.0)",
    "tifffile (==2024.5.10)",
    "tinycss2 (==1.4.0)",
    "tomli (==2.0.1)",
    "toolz (==1.0.0)",
    "torch (==2.7.0)",
    "torchmetrics (==1.7.1)",
    "torchvision (==0.22.0)",
    "tornado (==6.5)",
    "tqdm (==4.67.1)",
    "traitlets (==5.14.3)",
    "triton (==3.3.0)",
    "typing-extensions (==4.11.0)",
    "tzdata (==2024.1)",
    "ultralytics (==8.3.105)",
    "ultralytics-thop (==2.0.14)",
    "urllib3 (==2.3.0)",
    "virtualenv (==20.29.1)",
    "wcwidth (==0.2.13)",
    "webencodings (==0.5.1)",
    "werkzeug (==3.1.3)",
    "xarray (==2024.7.0)",
    "xarray-einstats (==0.7.0)",
    "xyzservices (==2025.1.0)",
    "yarl (==1.19.0)",
    "yolov5 (==7.0.14)",
    "zarr (==2.18.3)",
    "zipp (==3.21.0)",
    "sep (>=1.4.1,<2.0.0)",
    "bliss-toolkit (>=0.3,<0.4) ; python_version >= \"3.12\" and python_version < \"4.0\""
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
